# .gitlab-ci.yml

# Define stages
stages:
  - build
  - test
  - deploy

build: 
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build

    

# Define job variables
# variables:
#   APP_NAME: "your-app-name"
#   DOCKER_IMAGE_TAG: "$CI_COMMIT_SHA"
#   DOCKER_REGISTRY: "your-docker-registry"
#   DOCKER_IMAGE_NAME: "$DOCKER_REGISTRY/$APP_NAME"

# Job: Build
# build:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker build -t "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" .
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
#     - docker push "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"

# Job: Test
# test:
#   stage: test
#   image: node:latest
#   script:
#     - npm install
#     - npm run test

# Job: Deploy
# deploy:
#   stage: deploy
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$DOCKER_REGISTRY"
#     - docker pull "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
#     - docker run --rm -d -p 80:80 "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG"
